module.exports = {
  content: [
    "./App.{js,jsx}",
    "./app/**/*.{js,jsx}",
    "./components/**/*.{js,jsx}",
  ],
  presets: [require("nativewind/preset")],

  theme: {
    extend: {
      fontSize: {
        xs: "14px",
        sm: "16px",
        base: "18px",
        lg: "20px",
        xl: "24px",
      },
      fontFamily: {
        normal: ["Poppins-Light"],
        regular: ["Poppins-Regular"],
        medium: ["Poppins-Medium"],
        semibold: ["Poppins-SemiBold"],
        bold: ["Poppins-Bold"],
        extraBold: ["Poppins-ExtraBold"],
      },
      colors: {
        "surface-container-lowest": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "on-background": "#0b1c30",
        background: "#f5f9ff",
        "on-error": "#ffffff",
        "on-primary-container": "#eeefff",
        tertiary: "#51565b",
        error: "#ba1a1a",
        outline: "#737686",
        "outline-variant": "#c3c6d7",
        "on-secondary-container": "#5c647a",
        "surface-container-high": "#dce9ff",
        "on-surface-variant": "#434655",
        "primary-fixed-dim": "#b4c5ff",
        "surface-container-low": "#eff4ff",
        "primary-fixed": "#dbe1ff",
        "secondary-container": "#dae2fd",
        "surface-container": "#e5eeff",
        "on-primary": "#ffffff",
        "surface-container-highest": "#d3e4fe",
        "on-secondary": "#ffffff",
        surface: "#f8f9ff",
        primary: "#004ac6",
        "on-surface": "#0b1c30",
        "on-tertiary": "#ffffff",
        "primary-container": "#2563eb",
        secondary: "#565e74",
        "surface-variant": "#d3e4fe",
        "secondary-fixed": "#dae2fd",
        // kept from your theme.js — not in the HTML palette
        emerald: "#10b981",
        amber: "#b45309",
      },
      borderRadius: {
        DEFAULT: "4px",
        lg: "8px",
        xl: "12px",
        "2xl": "16px",
        full: "9999px",
      },
      spacing: {
        xs: "4px",
        sm: "8px",
        base: "8px",
        md: "16px",
        "card-gap": "12px",
        lg: "24px",
        xl: "32px",
        "container-padding": "16px",
      },
      fontFamily: {
        // requires Inter loaded via expo-font / @expo-google-fonts/inter —
        // ping me if you want that setup added
        sans: ["Inter"],
      },
      fontSize: {
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-caps": [
          "12px",
          { lineHeight: "16px", letterSpacing: "0.5px", fontWeight: "600" },
        ],
        "headline-lg-mobile": [
          "20px",
          { lineHeight: "28px", fontWeight: "600" },
        ],
        "headline-md": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "headline-lg": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "display-kpi": ["32px", { lineHeight: "40px", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-muted": ["12px", { lineHeight: "16px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
